### PR TITLE
Fix Typo in Utils.py

### PR DESCRIPTION
**Pull request by mariaWitch**
Should Fully Solve #86
There was a typo in the component list which meant that t2v steps and samplers would always remain at their default values. And we were passing an empty script input array, when there are in fact txt2vid scripts, thereby causing tons of errors by not at least having the script values being populated.

### CODE REVIEW

**Comment by volotat** [comment]
Thank you for spotting the problem. Can you elaborate why we need to create 'override_settings' and 'custom_inputs' for txt2vid mode, considering they are not used there?

**Comment by mariaWitch** [comment]
The need for them is that we are passing them by default. The scripts/extensions will error if nothing is passed. They need values to be passed, and the only way to do that, from what I can see is copying the way it is done in v2v, otherwise, you will have to account for every extension out there.

**Comment by volotat** [comment]
Got it. There is one problem though. When I try to use ControlNet in txt2vid it does not work for the first iteration and spits this error:

```
Error running process: /media/alex/ded3efe6-5825-429d-ac89-7ded676a2b6d/Github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/media/alex/ded3efe6-5825-429d-ac89-7ded676a2b6d/Github/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/media/alex/ded3efe6-5825-429d-ac89-7ded676a2b6d/Github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1122, in process
    raise ValueError('controlnet is enabled but no input image is given')
ValueError: controlnet is enabled but no input image is given
```
The input image is set in the ui. Of course we could avoid that by simply using image as a starting point, but it would be nice to have it working without it. Do you have ideas how to fix it?

**Comment by volotat** [comment]
I found the cause of the issue. It turns out that only v2v script params were actually passed to the processing method. Resolved an issue and found out that combining text to video with a control net is a really good idea and allows me to create videos like this using a single image as a guide.

https://github.com/volotat/SD-CN-Animation/assets/14307880/d467987b-5623-4bc6-9b3a-11e0c814b2a1

**Pull request merged**
